package spelllist;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import spelllist.Spell;

import spelllist.SpellDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig spellDaoConfig;

    private final SpellDao spellDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        spellDaoConfig = daoConfigMap.get(SpellDao.class).clone();
        spellDaoConfig.initIdentityScope(type);

        spellDao = new SpellDao(spellDaoConfig, this);

        registerDao(Spell.class, spellDao);
    }
    
    public void clear() {
        spellDaoConfig.getIdentityScope().clear();
    }

    public SpellDao getSpellDao() {
        return spellDao;
    }

}
