package spelllist;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SPELL.
 */
public class Spell {

    private Long id;
    private String name;
    private Integer castingCost;
    private String actionType;
    private Integer minRange;
    private Integer maxRange;
    private String effect;

    public Spell() {
    }

    public Spell(Long id) {
        this.id = id;
    }

    public Spell(Long id, String name, Integer castingCost, String actionType, Integer minRange, Integer maxRange, String effect) {
        this.id = id;
        this.name = name;
        this.castingCost = castingCost;
        this.actionType = actionType;
        this.minRange = minRange;
        this.maxRange = maxRange;
        this.effect = effect;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getCastingCost() {
        return castingCost;
    }

    public void setCastingCost(Integer castingCost) {
        this.castingCost = castingCost;
    }

    public String getActionType() {
        return actionType;
    }

    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    public Integer getMinRange() {
        return minRange;
    }

    public void setMinRange(Integer minRange) {
        this.minRange = minRange;
    }

    public Integer getMaxRange() {
        return maxRange;
    }

    public void setMaxRange(Integer maxRange) {
        this.maxRange = maxRange;
    }

    public String getEffect() {
        return effect;
    }

    public void setEffect(String effect) {
        this.effect = effect;
    }

}
